### ISSUE TITLE
No License Definition

### ISSUE THREAD

**Issue by jtroe** [IntelliTect/Coalesce#1]
I'm interested in using this and potentially contributing.  Can you add a open-source license, preferably something permissive like MIT?

**Comment by GrantErickson** [comment]
Jason, we have been working on this. Gauging interest. I will let you know soon. 

BTW: How did you stumble upon it?

**Comment by GrantErickson** [comment]
@jtroe sorry that took so long. I just got to it. It now has an Apache 2.0 license.
