### ISSUE TITLE
Filter in BaseApiController performing incorrect conversion of datetimeoffset

### ISSUE THREAD

**Issue by finlaysonc** [IntelliTect/Coalesce#10]
Reproduced as follows:
In VBCN test site, I set up three meal entities - 6/8/2017 11:12pm, 6/9/2017 12:00am and 6/9/2017 12:58am.  
The following query should return only those on 6/8, but it is returning all three:
http://vbcn-test.azurewebsites.net/api/Meal/customlist?fields=Mealid,mealtime&MealTime=2017-06-8

Returns:
`{
  "wasSuccessful": true,
  "message": null,
  "page": 1,
  "pageSize": 25,
  "pageCount": 1,
  "totalCount": 3,
  "list": [
    {
      "mealId": 6,
      "mealTime": "2017-06-09T00:00:00-07:00"
    },
    {
      "mealId": 7,
      "mealTime": "2017-06-09T00:58:00-07:00"
    },
    {
      "mealId": 14,
      "mealTime": "2017-06-08T23:12:00-07:00"
    }
  ]
}`

The offending line is in the BaseApiController where the following is done:
`DateTimeOffset dateTimeOffset = new DateTimeOffset(parsedValue, timeZone.BaseUtcOffset);`

Doing it in this manner does not account for daylight savings time.  So 6/8/2017 is -7 GMT because it is Pacific Daylight, but this will always convert to 6/8/2017 -8GMT.  To account for daylight savings, instead simply use:
          `TimeZoneInfo.ConvertTime(parsedValue, CurrentTimeZone);`

**Comment by GrantErickson** [comment]
@finlaysonc thanks for the update and contribution to the project. Just make sure this accounts for any time zone information passed back from the client.
