### ISSUE TITLE
Change CI/CD process to Azure Pipelines (abandon AppVeyor)

### ISSUE THREAD

**Issue by ascott18** [IntelliTect/Coalesce#101]
https://azure.microsoft.com/en-us/blog/announcing-azure-pipelines-with-unlimited-ci-cd-minutes-for-open-source/

**Comment by ascott18** [comment]
@vtbassmatt We've got our build setup now, but it appears to be consuming our minutes for private projects, despite being a public project. The project did used to be private, but we changed it to public:

https://intellitect.visualstudio.com/Coalesce/_build?definitionId=47

![image](https://user-images.githubusercontent.com/5017521/45896702-c3538500-bd89-11e8-85d3-b8216c95f1ad.png)

When I click on "View in-progress jobs" under Private projects, Microsoft-hosted while the build is running, the builds for Coalesce do not appear. When I click on "View in-progress jobs" for Public projects, Microsoft-hosted, the builds for Coalesce DO appear. Despite this, it is still consuming our minutes for private projects. Any ideas?

**Comment by vtbassmatt** [comment]
First off, sorry that I didn't see this until just now!

Hmm. We basically check for two things: 1) is the project that the build is part of public? and 2) is the source code public, whether that's in an Azure Repo or a GitHub public repo? Both of those appear to be true in your case, so we may have a bug. I will follow up.

**Comment by vtbassmatt** [comment]
We got you straightened out here, right? One of our engineers jumped on the bug right away and figured out what was happening, but I haven't seen the status on rolling out the fix.

**Comment by ascott18** [comment]
@vtbassmatt Looks like its fixed now - just ran a build and it didn't consume any private minutes.

Thanks so much for looking into this for us, and thanks for reaching out in the first place!
