### ISSUE TITLE
Edge case: "The SqlParameter is already contained by another SqlParameterCollection."

### ISSUE THREAD

**Issue by adamskt** [IntelliTect/Coalesce#106]
This is a total edge-case, but I think it at least deserves some consideration or documentation.  Here is an example project that illustrates the issue: https://github.com/IntelliTect/MarsError  

Repro steps:
- Set L42 to "WorkingConnection" in Startup.cs
- It works (search for something on index page with two commonly-used letters)
- Set L42 to "BrokenConnection" in Startup.cs
- It breaks (search for something on index page with two commonly-used letters)

Intersection of characteristics to produce broken-ness:
* MultipleActiveResultSets=true
* Model has some kind of relationship
* StandardDataSource impl overrides ApplyListSearchTerm with some usage of .FromSql and SqlParameters.

**Comment by adamskt** [comment]
This might be related to https://github.com/aspnet/EntityFrameworkCore/issues/11370

**Comment by ascott18** [comment]
This has been fixed upstream in EF Core, per the issue you linked.

**Comment by adamskt** [comment]
Shall I delete the referenced repro repo?

**Comment by ascott18** [comment]
That probably sounds OK. Note that I didn't actually test the repro repo using newer versions of EF core.
