### ISSUE TITLE
Remove IntelliTect.Nlog.Extensions (?)

### ISSUE THREAD

**Issue by finlaysonc** [IntelliTect/Coalesce#11]
- Doesn't appear to be used by Coalesce
- likely not by anything else (project is outdated)? 
- Since Coalesce doesn't rely on it, if we want to keep it, it should probably reside in our IntelliTect grab bag utility library - which I believe is still in IntelliTect's TFS wold....we may want to move this to github (but that's a separate issue)

**Comment by GrantErickson** [comment]
Unless we are using this it should be removed. Too specific.
Grant
