### ISSUE TITLE
Allow CurrentTimeZone in Coalesce to be configurable instead of hardcoded to pacific

### ISSUE THREAD

**Issue by finlaysonc** [IntelliTect/Coalesce#12]
As of now, the coalesce framework is hardcoded to convert and persist all times in Pacific in the base controller via the CurrentTimeZone property. This is not inherently a problem per se, however, there may be some scenarios where clients want to to store them in a different offset.  The reasons could be either simply policy related due to an organization standards (e.g. always store in UTC), or a more pragmatic reason.  Hagadone is a good example of a pragmatic scenario. Say, for example, Hagdone were located in Boston.  All information about cruises would be local to Boston.  If all times are stored in as eastern, then it would help out individuals performing basic reports in Excel or whatever as they don't need to worry about what the any conversoin gymnastics - everything dumped out of the DB is already eastern.   

Another pragmatic reason may be because of 3rd party restrictions.  Kendo grids for example, cannot deal with DateTimeOffset's and they assume everything is in UTC.  So gymnastics have to be performed somewhere.

**Comment by ascott18** [comment]
Done. http://coalesce.readthedocs.io/en/latest/pages/topics/startup/
