### ISSUE TITLE
Make Roles property on SecurityAttribute a string array

### ISSUE THREAD

**Issue by adamskt** [IntelliTect/Coalesce#13]
Rather than just "knowing" to store multiple roles as CSV in the Roles property, make it a params string array then convert it to CSV in a ctor for the attribute.
Instead of:
`[Read(Roles = nameof(Roles.DeploymentReader) + "," + nameof(Roles.DeploymentRunner))]`

This:
`[Read(nameof(Roles.DeploymentReader), nameof(Roles.DeploymentRunner))]`

**Comment by adamskt** [comment]
Example impl:

Make Roles property non-virtual

```csharp
    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Class)]
    public class ReadAttribute: SecurityAttribute
    {
        public ReadAttribute()
        {
            
        }

        public ReadAttribute(params string [] roles)
        {
            Roles = string.Join(",", roles);
        }
    }

**Comment by GrantErickson** [comment]
We just need to make sure this works with the Roslyn parser the way we are using it.
