### ISSUE TITLE
Docs: Add a summary page link to the top of the left hand nav list

### ISSUE THREAD

**Issue by GrantErickson** [IntelliTect/Coalesce#156]
I went to the docs and started clicking around reading stuff and then decided I wanted an overview. What does this thing really do anyway? I know we have written about 10 of these. However, the top item on the list was about EF Models.
I never realized that I could click on the Coalesce title at the top. Doesn't seem super discoverable since it really isn't in the nav area. I wonder if we should/can put a link to the summary as the top documentation option to make it clear how to find that. 
Also wondering if we should have a link to the GitHub repo on this page so it is clear where to find it.

**Comment by ascott18** [comment]
It'll require some hacks to the theme, but probably doable.

I can't just list the home page in the table of contents normally, because the home page is what defines the table of contents. If I do include it, it explodes.

**Comment by ascott18** [comment]
This exists since the docs moved to GH pages
