### ISSUE TITLE
Sdk.props error after upgrading to 15.3.x

### ISSUE THREAD

**Issue by howardderekl** [IntelliTect/Coalesce#19]
See workaround involving adding a user environment variable for: VSINSTALLDIR

[Github Microsoft workaround](https://github.com/Microsoft/msbuild/issues/2369#issuecomment-323959021)

**Comment by howardderekl** [comment]
Looks like they have implemented a fix for this issue:

[Link to Pull request](https://github.com/Microsoft/msbuild/pull/2454)

**Comment by adamskt** [comment]
Targeted for [Milestone 15.5](https://github.com/Microsoft/msbuild/milestone/17)

**Comment by howardderekl** [comment]
After installing the latest update today, my sdk's folder was removed.  Received the Sdk.props error again

Had to copy the sdk's folders from the dotnet sdk's folder into the location the msbuild was looking for.

**Comment by ascott18** [comment]
No longer a problem in the latest 2.0 since we don't use MsBuildWorkspace anymore.

**Comment by howardderekl** [comment]
Good work Andrew!
