### ISSUE TITLE
Unexpected 404 on search

### ISSUE THREAD

**Issue by BenjaminMichaelis** [IntelliTect/Coalesce#248]
If you search something and hit enter (as the bottom of the search window seems to indicate is possible) it returns a 404. You can also just open up the search window and hit enter and the same result occurs.

Expected behavior is to either do nothing (aka execute the search query) or to select the item that is currently highlighted.

![coalescesearchdoc](https://user-images.githubusercontent.com/22186029/183501315-2995d9da-86c8-447e-b844-7b4eeff20624.gif)

**Comment by ascott18** [comment]
Thanks. This is a known upstream issue. https://github.com/vuepress/vuepress-next/issues/1024

**Comment by ascott18** [comment]
Should be fixed by e7cb79e732b5b6a9fa17605624760eb321f219aa.
