### ISSUE TITLE
Hitting enter in search unexpectedly stops query or selects item from previous query

### ISSUE THREAD

**Issue by BenjaminMichaelis** [IntelliTect/Coalesce#261]
The updating for this searching feels unexpected. When I hit enter, I expect the search query to finish running or to select the result if there is one available/found, not to stop and tell me there are no results found, and when I delete a query and search something else and hit enter, I don't expect it to select what was found for my text before I changed it.

![coalescesearching](https://user-images.githubusercontent.com/22186029/197307085-5bcb3dfd-4ec5-4b87-853a-a0011a50b4f8.gif)

**Comment by ascott18** [comment]
This is an upstream issue - https://github.com/algolia/docsearch/issues/1639
