### ISSUE TITLE
C# DTO generation fails if namespace contains a model name

### ISSUE THREAD

**Issue by adamskt** [IntelliTect/Coalesce#28]
I discovered this when bringing the SC ClientRates app up to using alpha-122 of the Nuget package.

Given a solution namespace of "SouthernCross.ClientRates.[Web/Data]":

The Client model has a property of `ICollection<Rate> Rates`.

Expected generated output in ClientDto.g.cs:
`public System.Collections.Generic.ICollection<SouthernCross.ClientRates.Web.Models.RateDtoGen> Rates { get; set; }`

Actual output:
`public System.Collections.Generic.ICollection<SouthernCross.ClientRateDtoGens.Data.Models.RateDtoGen> Rates { get; set; }`

I believe the Regex [here](https://github.com/IntelliTect/Coalesce/blob/2.0/src/IntelliTect.Coalesce/TypeDefinition/TypeViewModel.cs#L244) is replacing on the first "Rate" in the solution namespace which yields generated code that won't compile.

**Comment by ascott18** [comment]
Yeah, I figured this would happen eventually. There are several places throughout the code gen that are very tenuous when it comes to how things are named. The DTOs names (and that property you linked in particular) is one of the biggest such cases.

A simple short-term fix would be to force the regex to only operate at the end of a qualified name - only match on character sequences that come after a dot and have a non-letter, non-dot character after (whitespace and a closing angle brakcet are the only two symbols I could think would be valid at the end of a fually qualified type name)

**Comment by ascott18** [comment]
Let me know if the fix I checked into 2.0 fixes this issue for you.

**Comment by adamskt** [comment]
That fixed it!
