### ISSUE TITLE
DateTime-Picker HideDetails Property

### ISSUE THREAD

**Issue by TylerRose** [IntelliTect/Coalesce#295]
The `hide-details` property doesn't pass through to the underlying Vuetify component.

Seen in attributes:
![image](https://github.com/IntelliTect/Coalesce/assets/47163327/6df251fb-22e0-473f-85c1-479ae30a7ba9)
But not in the Vuetify component:
![image](https://github.com/IntelliTect/Coalesce/assets/47163327/59dbe960-19f8-4403-a5be-5253edaade12)

**Comment by ascott18** [comment]
Can no longer reproduce this. I believe it was fixed with this change: https://github.com/IntelliTect/Coalesce/commit/1f9b1290ec3a5416e527901613424bc2d01cb0fb#diff-8b493e32489d620030cfcf14117975bc06cc3eddd9387d2d47704d2f243642dcR204
