### ISSUE TITLE
Setters called when no setter on property

### ISSUE THREAD

**Issue by MagicTrevor** [IntelliTect/Coalesce#3]
I think line 86 of ClassDto.cshtml should call `CanWrite` instead of `CanRead` in order to verify a setter exists for a property before generating the setter call.

**Comment by ascott18** [comment]
Its correct the way it is.

If it was CanWrite, then getter-only properties would never be serialized to the DTO and sent out to the client. Line 86 is in the EF POCO to DTO mapping, not the method that maps the DTO back to the EF POCO. The DTO -> EF POCO mapping does correctly use CanWrite.
