### ISSUE TITLE
Usages card overlaps the Generated DTO Properties card on Security Overview page

### ISSUE THREAD

**Issue by meghanmae** [IntelliTect/Coalesce#333]
The[ usages card](https://github.com/IntelliTect/Coalesce/blob/9c0ab6b5ee7751505d67667f293bad5599f45abe/src/IntelliTect.Coalesce/Application/SecurityOverview.html#L289C28-L289C29) on the coalesce security overview page overlaps with the generated DTO properties card

![image](https://github.com/IntelliTect/Coalesce/assets/43832670/826b49a9-cfab-4fd0-a0c0-f57e19395f59)

**Comment by ascott18** [comment]
Fixed with #335
