### ISSUE TITLE
Handle Unsuccessful or null ItemResults

### ISSUE THREAD

**Issue by schuywalker** [IntelliTect/Coalesce#337]
We are writing this 'unsuccessful or null' code repeatedly throughout the Storming the Castle codebase, for any call that tries to access a field from a database call. What if there was a 'Resolve' method on ItemResult that did this for us, or an option to return results when unsuccessful automatically?
![image](https://github.com/IntelliTect/Coalesce/assets/11594868/5c1a84cf-3f8a-490e-9f9a-274451e569c4)

**Comment by ascott18** [comment]
Could you share an example of what a usage of the proposed API would look like?

**Comment by schuywalker** [comment]
The more I think about it, the less I can see a way to implement something like this. There could be an extensible unsuccessful method: `if (ItemResult.WasUnsuccessful(result)) { return result.Message; }` that would perform a default set of checks. but that probably doesn't save enough time to be worth implementing.
