### ISSUE TITLE
Implementing the same interface with different type parameters.

### ISSUE THREAD

**Issue by BenjaminMichaelis** [IntelliTect/Coalesce#353]
If I implement two different type parameters for a restriction

```C#
public class ProjectManagerRestrictions(AppDbContext db) : IPropertyRestriction<Project>, IPropertyRestriction<Assignment>
```

I then still have to still do an implementation for type object (from the derived class).

```C#
bool IPropertyRestriction.UserCanRead(IMappingContext context, string propertyName, object model)
{
    return model switch
    {
        User user => ((IPropertyRestriction<User>)this).UserCanRead(context, propertyName, user),
        Assignment assignment => ((IPropertyRestriction<Assignment>)this).UserCanRead(context, propertyName, assignment),
        _ => throw new NotImplementedException(),
    };
}
```

Why do we have a interface that takes `object` for the model at all?

**Comment by BenjaminMichaelis** [comment]
I made a little sample with my thoughts here: https://github.com/IntelliTect/Coalesce/pull/354

**Comment by ascott18** [comment]
> Why do we have a interface that takes object for the model at all?

For exactly the use case you're trying to implement - for when the logic applies to properties from multiple unrelated types. `IPropertyRestriction` is the "true" interface. `IPropertyRestriction<>` was a concession for "ease of use" for common scenarios where a restriction is specific to properties on a single object type.

**Comment by BenjaminMichaelis** [comment]
I'm still not quite clear why we need the base class generic object type. If you want to go generic object on it, you implement via IPropertyRestriction<object> as your workaround. I want to explicitly implement both interface types in my case, but it seems redundant to implement the base class, especially because I don't think the base class will get called (But I am saying this all without the internal knowledge of how coalesce works of course )

**Comment by ascott18** [comment]
Removing CanRead/CanWrite from IPropertyRestriction as in #354 breaks the guarantees provided by the interface.

I can now write this:
``` c#
public class TestRestriction() : IPropertyRestriction { }
```

and there are no errors in my model, but the generated code is now broken because it is relying on "magic signatures" to find a matching CanRead/CanWrite method on the restriction that is now no longer guaranteed to be there by the interface.

![image](https://github.com/IntelliTect/Coalesce/assets/5017521/94cc9b9f-1277-4e1e-8e32-3445ab176931)

**Comment by ascott18** [comment]
Closing this out as there's no action that can be taken here.
