### ISSUE TITLE
Wrong colors on some code samples when navigated through search box

### ISSUE THREAD

**Issue by BenjaminMichaelis** [IntelliTect/Coalesce#368]
Similar to #356 but different repro steps.

When I search for some things, some of the code samples load with the wrong colors, but when I refresh or hit the link directly, it works fine.

Tested on Chrome, firefox, and Brave.

https://github.com/IntelliTect/Coalesce/assets/22186029/5d820f8c-b816-4da9-9381-7cd516b2f94f

**Comment by ascott18** [comment]
This seems to have gotten fixed with c6f598e48e3ccbc937a4724815519090fbdac18e
