### ISSUE TITLE
Allow model properties to be called "parent"

### ISSUE THREAD

**Issue by adamskt** [IntelliTect/Coalesce#40]
The Knockout templates already add a property in TypeScript called "parent", so your properties get overwritten.

**Comment by GrantErickson** [comment]
If we solve this is it would probably be to change the name of the model Parent property to minimize breaking changes. This has been fixed in the Vue implementation. If it turns into an issue we will look at it.

**Comment by ascott18** [comment]
Closing out old Knockout issue
