### ISSUE TITLE
ListResult constructor taking in ApiResult doesn't map total count, page, and page size values

### ISSUE THREAD

**Issue by IPCAshlyn** [IntelliTect/Coalesce#445]
When using a generated controller method that returns a ListResult does not return the total count, page, and page size values correctly. 

The generated controller method calls into the custom implemented method on the model to get results from the database using Entity Framework. When the results from said model method are returned to the generated controller method, they are passed into a ListResult<GeneratedType>() constructor in the form of ListResult<Type Returned from Model Method>, which routes to the `public ListResult(ApiResult result) : base(result) { }` version of the constructor. Example code:
```
var _methodResult = (call to model method)
var _result = new ListResult<DtoGen>(_methodResult);
_result.List = _methodResult.List?.ToList().Select(o => Mapper.MapToDto<Model Returned Type, DtoGen>(o, _mappingConext, includeTree ?? _methodResult.IncludeTree)).ToList();
return _result;
```

**Comment by ascott18** [comment]
Your timing is impeccable! Fixed in v5, which just released moments ago. The fix is technically a breaking change because it changed the constructors a little bit, so this was great to get in for v5.
