### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by ascott18** [IntelliTect/Coalesce#45]
- [x] Create document, probably based on a good template that I'm sure is out there somewhere
- [x] Include instructions on development environment, debugging, etc.
- [x] Include instructions on setting up VSCode for editing the documentation.

**Comment by adamskt** [comment]
I will steal the one from the IntelliTect library repo (which I stole from the Cake project originally)

**Comment by adamskt** [comment]
Regarding VSCode and doc editing: do you mean installing python, pip, sphinx, restructuredtext_lint and the LexStudio reStructuredText plugin?  Or more general?

**Comment by ascott18** [comment]
Yes, that exactly.
