### ISSUE TITLE
Returning an ICollection<T> from a method in the T class causes invalid TypeScript

### ISSUE THREAD

**Issue by GrantErickson** [IntelliTect/Coalesce#47]
The generated TypeScript is calling RebuildArray which is expecting the result type to be an ObservableArray rather than just a plain Observable. 

This should typically be handled by a DataSource and is somewhat left over from the old days before DataSources. However, it should probably work.
The question is how it should work:
1. Put array object and put it in an Observable.
2. Put each object in an ObservableArray.

**Comment by ascott18** [comment]
Fixed by c1e916e4
