### ISSUE TITLE
Remove or Fix Views\Api\EditorHtml.cshtml

### ISSUE THREAD

**Issue by adamskt** [IntelliTect/Coalesce#53]
This file is copied during generation and makes use of public properties that were deleted in [839d49fb](https://github.com/IntelliTect/Coalesce/commit/839d49fb40e8aacd8aa9bcfb636c23bc3feb674b#diff-7990bb213f5facac029c587c43476c04L42-L52).  This view is rarely used, but breaks sites that require pre-compiled views.

**Comment by ascott18** [comment]
Fixed in 8eeea53, but we should still evaluate whether we should keep EditorHtml. @GrantErickson, thoughts?

Also moved EditorHtml and Docs to generate into Views/Generated/Api instead of Views/Api

**Comment by GrantErickson** [comment]
This is used in a few spots. Sounds like @ascott18 cleaned up the major issue with it not compiling. This will eventually become obsolete with the way Vue works now.

**Comment by ascott18** [comment]
Closing out old Knockout issue
