### ISSUE TITLE
Docs.cshtml template broken

### ISSUE THREAD

**Issue by adamskt** [IntelliTect/Coalesce#64]
In commit 4fc35f42, the ```HasClientValidation``` property was removed from ```PropertyViewModel```.  The template for Docs.cshtml relies on [this property](https://github.com/IntelliTect/Coalesce/blob/32f4f479091fdbdc9f5f0ee7672d1231f98730f3/src/IntelliTect.Coalesce.CodeGeneration.Knockout/Templates/Views/Api/Docs.cshtml#L125).  This only breaks builds that precompile the views (deploying builds).  We need a way to see that this is broken before runtime errors.

**Comment by ascott18** [comment]
ugh

**Comment by ascott18** [comment]
Fixed in 42d0bc66  by just removing that column since it wasn't conveying any meaningful information anyway.

**Comment by ascott18** [comment]
Related #53.

As far as preventing this in the future, I really don't know. I don't think that `MvcRazorCompileOnPublish` would be useful since this isn't in a web project that is being published - its existence in the code generation project is essentially as just a static file that we copy over.

**Comment by GrantErickson** [comment]
Yeah, I saw this the other day as well. I still miss those pages, but maybe no one else does.
