### ISSUE TITLE
Better support on admin pages when a row has many child rows

### ISSUE THREAD

**Issue by GrantErickson** [IntelliTect/Coalesce#7]
The admin pages by default show the number of related child rows. Currently, there isn't a good way to do this aside from getting all the rows. If the number of rows is large, this causes problems. It would good to handle this more graciously.
Some options. 
1. Allow for not showing this information via a flag.
2. Allow for just querying the count rather than all the rows. Not sure that EF Core supports yet.
3. Allow for automatically managing a row count field that stays updated automatically.

**Comment by ascott18** [comment]
General guidance here would be to not add collection navigation properties for relationships that can grow arbitrarily large. If we need something else here then we can re-open this in the future.
