### ISSUE TITLE
Knockout: Should saving cancel pending autosave

### ISSUE THREAD

**Issue by GrantErickson** [IntelliTect/Coalesce#77]
Under default conditions, if a property is changed, a save gets queued. Before this save executes, if save is explicitly called, should this cancel the pending save? Any reasons why this shouldn't be the behavior?

**Comment by ascott18** [comment]
Assuming you're referring to the [`saveTimeout`](https://github.com/IntelliTect/Coalesce/blob/dev/src/IntelliTect.Coalesce.CodeGeneration.Knockout/Templates/Scripts/Coalesce/coalesce.ko.base.ts#L765) and not the actual AJAX request, then yes, this sounds reasonable

**Comment by ascott18** [comment]
Fixed in #91
