### ISSUE TITLE
Rare potential issue: CrudContext can get an incorrect ClaimsPrincipal if injected too early.

### ISSUE THREAD

**Issue by ascott18** [IntelliTect/Coalesce#78]
If `CrudContext` is injected before `HttpContext.User` gets set (it gets set after authentication is handled), `CrudContext` will end up with a `ClaimsPrincipal` that is effectively empty. Since `CrudContext` grabs the current value of `HttpContext.User` at the moment of instantiation, this never gets updated.

This can be easily worked around by just not injecting `CrudContext` into anything that is part of the pipeline pre-authentication. However, it would be nice if you weren't allowed to shoot yourself in the foot like this. For example, I had an `IClaimsTransformer` that injected my custom `RoleService`. `RoleService` then had a dependency on `CrudContext` (because I wanted to get the current user in the `RoleService`, and `CrudContext` seemed like a viable candidate for this). Because the `IClaimsTransformer` is instantiated during the auth pipeline but before `HttpContext.User` is set, we ended up with the wrong user in our Coalesce data sources/behaviors.

A fix would be to change `CrudContext.User` to invoke a resolver function instead of using the value of a stored property. The creation of `CrudContext` in the service collection extensions would then need to be changed to pass a resolver function instead of a hard moment-in-time reference to the current `ClaimsPrincipal` held by the `HttpContext`.

**Comment by adamskt** [comment]
What about changing the `CrudContext` to depend on an injected `IHttpContextAccessor` to get the current  `ClaimsPrincipal`?  This would require that ConfigureServices always had `services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();`

**Comment by ascott18** [comment]
Yeah, this was my thought on how to go about this. We basically need to support two constructors, or maybe even two different implementation classes (although that's not too nice for usability). One that takes an `IHttpContextAccessor` to resolve the user, and one that just takes a `ClaimsPrincipal` for the user.

The reason why there should still be a ctor where you pass in the user, context, etc. explicitly is for testing. I want to test a data source, and to do that I need to satisfy its single ctor parameter of a `CrudContext`. For this `CrudContext`, I might want to pass in my in-memory `DbContext` for testing, as well as a local, test-specific `ClaimsPrincipal` instance because I'm testing the security of my data source.

**Comment by adamskt** [comment]
What do you think about making the `ClaimsPrincipal` ctor internal and using `InternalsVisibleTo` for testing?  This way we aren't polluting the API with a method that really only is for testing (and leaving Chekhov's gun out for users to play with).

**Comment by ascott18** [comment]
I'm referring to tests in consumers' projects (testing your own custom data sources), not so much tests against the core `IntelliTect.Coalesce` library.

Plus, there are still valid reasons to want to pass a ClaimsPrincipal manually in application code. If I need to instantiate a data source/behaviors class at runtime but outside of a context where I have the DI container (a bit far-fetched, I know), then a ctor with a ClaimsPrincipal would also be good to have around.

**Comment by GrantErickson** [comment]
Thanks for doing this Kelly. I will let Andrew review as well.
