### ISSUE TITLE
[Vue] Write Documentation

### ISSUE THREAD

**Issue by ascott18** [IntelliTect/Coalesce#80]
- [ ] Move the Knockout-specific docs into a Knockout section, put the Vue docs in a Vue section
- [ ] Metadata
- [ ] Models
- [ ] Api Clients
- [ ] ViewModels
- [ ] ListViewModels
- [ ] (Maybe) Knockout/Vue compare and contrast for key features

**Comment by ascott18** [comment]
Done, finally!

**Comment by GrantErickson** [comment]
Great work @ascott18!

**Comment by GrantErickson** [comment]
Find them at https://coalesce.readthedocs.io
