### ISSUE TITLE
Improve coalesce.intellitect.com

### ISSUE THREAD

**Issue by adamskt** [IntelliTect/Coalesce#85]
- [x] Remove out-of-date versions on website (ASP.NET Core 1.0, etc.)
- [x] Write content for the "Get Coalesce" page to use the starter project or the dotnet new templates.
- [x] Set up Let's Encrypt cert for coalesce.intellitect.com domain.
- [x] Fix footer to copyright for IntelliTect.
- [x] Link Docs links to https://coalesce.readthedocs.io/en/latest/
- [ ] Add to [awesome-dotnet](https://github.com/quozd/awesome-dotnet) list
- [x] Fix site `<title>` to not be "My ASP.NET Site"
- [x] Add links to GitHub repo

**Comment by ascott18** [comment]
Aye, it does need it badly.

I would be tempted to redo it entirely - the demo could be cooler, integrating some of the features we've added over the past 2+ years. I'd also be tempted to do it primarily in Vue (with a piece of it still in Knockout/MVC for a demo of the Knockout behavior, but overall make it a SPA with Vue). Something a bit more interesting than "cases", too.

**Comment by GrantErickson** [comment]
For sure. I like the idea of a good non-cases demo.

**Comment by ascott18** [comment]
One thing's for sure, though - we need an awesome logo.

**Comment by GrantErickson** [comment]
Maybe we should experiment with the logos of derived products to see if we can get something that is foundational.

**Comment by adamskt** [comment]
Added to awesome-dotnet in https://github.com/quozd/awesome-dotnet/pull/688

**Comment by adamskt** [comment]
Add to awesome-dotnet-core in thangchung/awesome-dotnet-core#420
