### ISSUE TITLE
Evaluate the future of the starter projects [WIP]

### ISSUE THREAD

**Issue by ascott18** [IntelliTect/Coalesce#90]
Right now, the starter projects exist, but so do the `dotnet new` template projects.

We probably don't have a need for the starter projects anymore, but links to them were added to the Coalesce.Web project's nav bar. Should we remove those links and archive the starter project repos?

@adamskt @GrantErickson

**Comment by adamskt** [comment]
As part of this, should we split apart the "brochureware" coalesce.intellitect.com site from the demo into separate repos?  I realize that the demo is in some ways a unit-test of changes to the code generation engine, but maybe a submodule ref is a better way to handle that?

Proposal Repos:

- IntelliTect\Coalesce containing:
  - IntelliTect.Coalesce
  - IntelliTect.Coalesce.Cli
  - IntelliTect.Coalesce.CodeGeneration
  - IntelliTect.Coalesce.CodeGeneration.Api
  - IntelliTect.Coalesce.CodeGeneration.Knockout
  - IntelliTect.Coalesce.CodeGeneration.Vue
  - IntelliTect.Coalesce.Knockout
  - IntelliTect.Coalesce.Tests
  - Submodules to:
    - Coalesce.Demo
  - Script to create local nugets with version 999.0.0
- IntelliTect\coalesce.intellitect.com containing:
  - Coalesce.IntelliTect.Com (brochureware site, razor pages?)
  - Submodules to:
    - Coalesce.Demo
- IntelliTect\Coalesce.Demo
  - Coalesce.Domain
  - Coalesce.Web
  - Coalesce.Web.Vue
  - coalesce-vue
  - In Debug, references local nugets v999.0.0, in Release falls through to public latest stable Nuget
- IntelliTect\Coalesce.KnockoutJS.Template
- IntelliTect\Coalesce.Vue.Template
- Archive Coalesce.Starter
- Archive Coalesce.Starter.Vue

**Comment by GrantErickson** [comment]
I think this should probably be split off and have another site. Maybe the demo has just a little bit of description (an about page), but more demo less 'marketing.'

**Comment by ascott18** [comment]
@adamskt coalesce-vue is a core library, not part of the demo. Its the npm package containing the common dependencies for the generated code for Vue.

For the demo, I think the ideal setup would to have both Vue and knockout in the same web project. They're split now, but there's no compelling reason for it other than that the Vue demo project (which isn't much of a demo of anything currently - more of a development sandbox) started out totally independent of the rest of the repo/solution, and only joined the fray after something became of the Vue code.

**Comment by adamskt** [comment]
@ascott18 has the Coalesce.Vue stuff made it into master, or is it still only in dev?  That's the only real barrier I can see to merging it into the Coalesce.Web project.

@GrantErickson what is the "this" in "I think *this* should be split off"?  (insert javascript `this` joke here)

**Comment by ascott18** [comment]
Yes, it is in master - just hasn't been pushed there in 3 months. While it is out there and available through use via the public NuGet.org feed, it isn't really "public" because it isn't documented, nor would I consider it complete.

**Comment by GrantErickson** [comment]
Touche...
var splitApp = function(app) {
    return app - this;
}
var demoApp = splitApp.call(marketingPart, wholeApp);

**Comment by adamskt** [comment]
This is turning out to be harder than I expected.  Since Coalesce.Demo depends on Coalesce, bringing it in as a submodule to the Coalesce repo proves to be problematic.  The only easy solution I can see would be to not have it be in the Coalesce project at all, and just reference the Coalesce nuget packages in the demo.  This ruins the experience of using the Demo as a "feature playground" for new features in Coalesce itself.  Anyone have any bright ideas?

**Comment by ascott18** [comment]
I think we may have derailed from the original issue a bit and bloated this one bigger than it should be.

For the secondary issue here of splitting the demo out, I think that having it standalone and referencing the nuget packages is what we want. There should be probably 3 web sites in total:

* coalesce.intellitect.com, including all the content it does today, minus a good deal of the gunk that's accumulated over the years as a result of it being a dev playground, plus a Vue-based demo as well (in the same site). This exists as its own repo.
* A Knockout-based playground in IntelliTect/Coalesce for playing around with features (i.e. what Coalesce.Web is now). This site never gets published anywhere, so we don't care about trashing it as development is done.
* A Vue-based playground in IntelliTect/Coalesce for playing around with features (i.e. what Coalesce.Web.Vue is now). This site never gets published anywhere, so we don't care about trashing it as development is done.

**Comment by ascott18** [comment]
There's nothing left to do on this now - coalesce.intellitect.com was shut down, and I've moved the playgrounds into their own folder in the main repo. #143 tracks possibly bringing the templates into the main repo.
