### ISSUE TITLE
Add note to docs about setting Knockout.Default[Date|DateTime|Time]Format

### ISSUE THREAD

**Issue by adamskt** [IntelliTect/Coalesce#93]
I recently discovered that if you set static properties like `Knockout.DefaultDateTimeFormat` to a value like `"M/D/YYYY h:mm a Z"` you will get localized offsets displayed on any `DateTimeOffset`-backed model fields.  Additionally, if you add the moment-timezone npm package, you can get three-letter, auto-corrected-for-DST abbreviations with a format string like `"M/D/YYYY h:mm a z"`, you can even force a specific conversion by including a script block like:
```
<script>
    /* Default this site to EST/EDT because of client location */
    moment.tz.setDefault("America/New_York");
</script>
```
We should write a quick blurb in the docs about how Coalesce handles `DateTimeOffset` in the DTOs and in the knockout bindings.

**Comment by ascott18** [comment]
Sounds good. We don't have any documentation at all for the `Knockout` binding helpers. Part of this is a feature of those, and part of this is just passing the format parameter to the `moment` binding: http://coalesce.readthedocs.io/en/latest/pages/generated/client/bindings/#moment
