### ISSUE TITLE
[Discussion] Evaluate the future of the CSV endpoints

### ISSUE THREAD

**Issue by ascott18** [IntelliTect/Coalesce#95]
Should these be removed entirely? Added as some kind of a plugin? Turned off behind an option?

Right now, the code for Vue has no support for these because their future has been uncertain. In my opinion, I don't think they really belong as part of the core functionality of Coalesce.

**Comment by adamskt** [comment]
If we want to make the data exposed by Coalesce available to multiple systems, CSV is a good lowest-common-denominator solution. It would be nice to make these providers pluggable, with support for:
- PowerBI-friendly JSON 
- Excel OOXML
- Read-only OData

**Comment by ascott18** [comment]
Perhaps adding support to the existing /list endpoint for other formats via `Accept` headers.

* `Accept: text/csv`
* `Accept: application/vnd.ms-excel`

OData is a more interesting case because it is opinionated about the request parameters, so it wouldn't fit the existing endpoints. Maybe a way to fit it in could be figured out with #98.

**Comment by ascott18** [comment]
After discussing with @GrantErickson, we're going to go ahead and remove the CSV endpoints. 

In the future, we may introduce some out-of-the-box plugins for the Vue admin pages that do not require any special server-side endpoints - these plugins would use the existing list and save endpoints to perform the download/upload functionality of the current CSV endpoints.
